export const products = [
  {
    id: 1,
    name: 'English Willow Bat — Grade 1 Pro',
    category: 'Bats',
    price: 4499,
    originalPrice: 5999,
    image: '/products/bat-1.jpg',
    icon: 'bat',
    tag: 'Bestseller',
    badge: 'Grade 1 English Willow',
    rating: 4.9,
    reviewsCount: 142,
    weight: '1180g (2lb 9oz)',
    grains: '8-10 straight grains',
    handle: '12-piece Semi-oval Cane',
    sweetSpot: 'Mid to Low (All-round)',
    description: 'Carved from top-tier hand-selected Grade 1 clefts. Extraordinary ping with full spine profile and 39mm power edges. Comes pre-knocked with anti-scuff protection.',
    inStock: true,
  },
  {
    id: 2,
    name: 'Kashmir Willow Bat — Club Edition',
    category: 'Bats',
    price: 1899,
    originalPrice: 2499,
    image: '/products/bat-2.jpg',
    icon: 'bat',
    tag: 'Popular',
    badge: 'Seasoned Kashmir Willow',
    rating: 4.7,
    reviewsCount: 89,
    weight: '1220g (2lb 11oz)',
    grains: 'Naturally seasoned',
    handle: '3-piece Singapore Cane',
    sweetSpot: 'Mid-blade swell',
    description: 'Durable, naturally air-dried Kashmir willow built for rigorous club net sessions, leather ball tournaments, and heavy training.',
    inStock: true,
  },
  {
    id: 3,
    name: 'Four-Piece Leather Match Ball (Red)',
    category: 'Balls',
    price: 649,
    originalPrice: 850,
    image: '/products/ball.jpg',
    icon: 'ball',
    tag: 'Match Grade',
    badge: 'Alum Tanned Leather',
    rating: 4.8,
    reviewsCount: 215,
    weight: '156g Regulation',
    grains: 'Prominent 80-stitch seam',
    handle: 'Cork & Worsted Core',
    sweetSpot: 'Pronounced swing seam',
    description: 'Hand-stitched with 4-piece alum-tanned premium steer hide. Retains shape and lacquer for 40+ overs under intense match conditions.',
    inStock: true,
  },
  {
    id: 4,
    name: 'Batting Pads — Pro Impact Guard',
    category: 'Protective Gear',
    price: 2199,
    originalPrice: 2899,
    image: '/products/pads.jpg',
    icon: 'pad',
    tag: 'High Density',
    badge: 'High-Density Cane & Foam',
    rating: 4.9,
    reviewsCount: 76,
    weight: 'Ultra-light 820g per pad',
    grains: 'Traditional 7-cane vertical',
    handle: 'Triple padded padded straps',
    sweetSpot: 'Moulded gel knee cup',
    description: 'Feather-light ergonomic protection tested against 140 km/h deliveries. Features breathable 3D airmesh and reinforced side wings.',
    inStock: true,
  },
  {
    id: 5,
    name: 'Batting Gloves — Shark-Tooth Split',
    category: 'Protective Gear',
    price: 1349,
    originalPrice: 1799,
    image: '/products/gloves.jpg',
    icon: 'glove',
    tag: 'Pro Choice',
    badge: 'Pittards Leather Palm',
    rating: 4.8,
    reviewsCount: 94,
    weight: 'Ultra-flexible split-finger',
    grains: 'Fibre-shield inserts',
    handle: 'Towelling sweatband wrist',
    sweetSpot: 'Thumb 3-piece shock block',
    description: 'Unrestricted wrist mobility with multi-flex finger cutouts and sheep leather palms for supreme bat grip and vibration dampening.',
    inStock: true,
  },
  {
    id: 6,
    name: 'Touring Kit Bag — Heavy Duty Wheels',
    category: 'Kit Bags',
    price: 2999,
    originalPrice: 3999,
    image: '/products/bag.jpg',
    icon: 'bag',
    tag: 'New Drop',
    badge: '1680D Ballistic Cordura',
    rating: 4.9,
    reviewsCount: 58,
    weight: 'Huge 110L Capacity',
    grains: 'Tractor heavy-duty wheels',
    handle: 'Dual padded haul handles',
    sweetSpot: 'External 2-bat padded sleeve',
    description: 'Massive capacity crafted with water-resistant 1680D nylon. Features 3 ventilated gear compartments, shoe pocket, and all-terrain wheels.',
    inStock: true,
  },
]
